export * from './LandingPage';
export * from './LoginPage';
export * from './SignupPage';
// export * from './SignupPages';
export * from './CustomerSupportPage';
export * from './UserDashboardPages';
export * from './ServiceManagementPages';
export * from './BillingAndPaymentsPages';
export * from './FeedbackPage';
export * from './NotificationPage';
export * from './UserProfilePage';
export * from './ForgetPasswordPages';
